name: score_board
description: 'A new Flutter project.'
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  shared_preferences: ^2.5.4
  auto_size_text: ^3.0.0
  flutter_bloc: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  config:
    enable-lldb-debugging: false
  uses-material-design: true
  assets:
    - assets/fonts/
  fonts:
    - family: BitcountSingle
      fonts:
        - asset: assets/fonts/BitcountSingle/BitcountSingle-Light.ttf
          weight: 300
        - asset: assets/fonts/BitcountSingle/BitcountSingle-Regular.ttf
          weight: 400
        - asset: assets/fonts/BitcountSingle/BitcountSingle-Medium.ttf
          weight: 500
        - asset: assets/fonts/BitcountSingle/BitcountSingle-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/BitcountSingle/BitcountSingle-Bold.ttf
          weight: 700
